version: '3'
services:
  conjur_pg:
    image: postgres:9.5

  conjur:
    image: cyberark/conjur:0.3.0-stable
    command: server -a dev -f /policy.yml
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres@conjur_pg/postgres
      CONJUR_DATA_KEY: 'WMfApcDBtocRWV+ZSUP3Tjr5XNU+Z2FdBb6BEezejIs='
    volumes:
      - ./conjur-policy.yml:/policy.yml
    depends_on:
      - conjur_pg

  conjur_client:
    image: cyberark/cli5
    environment:
      CONJUR_APPLIANCE_URL: http://conjur
      CONJUR_ACCOUNT: dev
      CONJUR_AUTHN_LOGIN: admin
      CONJUR_AUTHN_API_KEY:
    depends_on:
      - conjur

  pg:
    build:
      context: ../src/pg

  ansible_secretless:
    image: secretless-broker
    command: "-debug"
    environment:
      CONJUR_APPLIANCE_URL: http://conjur
      CONJUR_ACCOUNT: dev
      CONJUR_AUTHN_LOGIN: host/ansible
      CONJUR_AUTHN_API_KEY:
    volumes:
      - ./secretless_ansible.yml:/secretless.yml
      - ssh_agent:/sock
    depends_on:
      - conjur
      - pg

  ansible:
    build:
      context: ../src/ansible
    entrypoint: [ "summon2", "-f", "/secrets.yml" ]
    environment:
      SSH_AUTH_SOCK: /sock/.agent
      CONJUR_APPLIANCE_URL: http://conjur
      CONJUR_ACCOUNT: dev
      CONJUR_AUTHN_LOGIN: host/ansible
      CONJUR_AUTHN_API_KEY:
      SUMMON_PROVIDER: conjur
    volumes:
      - ssh_agent:/sock
      - ./ansible_secrets.yml:/secrets.yml
    depends_on:
      - pg
      - ansible_secretless

  myapp_secretless:
    image: secretless-broker
    command: "-debug"
    environment:
      CONJUR_APPLIANCE_URL: http://conjur
      CONJUR_ACCOUNT: dev
      CONJUR_AUTHN_LOGIN: host/myapp
      CONJUR_AUTHN_API_KEY:
    volumes:
      - ./secretless_myapp.yml:/secretless.yml
      - pg_socket:/sock
    depends_on:
      - conjur
      - pg

  myapp:
    build:
      context: ../src/myapp
    environment:
      DB_HOST: /var/run/postgresql
    ports:
      - 80
    volumes:
      - pg_socket:/var/run/postgresql
    depends_on:
      - myapp_secretless

  client:
    build:
      context: ../src/client

  myapp_tls:
    build:
      context: ../src/proxy_tls
    entrypoint: [ "/summon2", "-f", "/secrets.yml" ]
    environment:
      CONJUR_APPLIANCE_URL: http://conjur
      CONJUR_ACCOUNT: dev
      CONJUR_AUTHN_LOGIN: host/myapp_tls
      CONJUR_AUTHN_API_KEY:
      SUMMON_PROVIDER: conjur
      SSL_CERT_FILE: ./proxy_tls.pem
    command: "./proxy_tls myapp"
    volumes:
      - ../../../dist/linux/amd64/summon2:/summon2
      - ./myapp_tls_secrets.yml:/secrets.yml
    depends_on:
      - conjur
      - myapp

volumes:
  pg_socket:
  ssh_agent:
