version: '2.1'
services:
  pg:
    image: postgres:9.4

  conjur:
    image: cyberark/conjur:0.3.0-stable
    command: server -a dev -f /work/policy/conjur.yml
    environment:
      DATABASE_URL: postgres://postgres@pg/postgres
      CONJUR_DATA_KEY: 'WMfApcDBtocRWV+ZSUP3Tjr5XNU+Z2FdBb6BEezejIs='
    volumes:
      - .:/work
    depends_on:
      - pg

  cli5:
    image: conjurinc/cli5
    environment:
      CONJUR_APPLIANCE_URL: http://conjur
      CONJUR_ACCOUNT: dev
    depends_on:
      - conjur
    volumes:
      - .:/work

  admin_secretless:
    image: secretless
    environment:
      CONJUR_APPLIANCE_URL: http://conjur
      CONJUR_ACCOUNT: dev
      CONJUR_AUTHN_LOGIN: alice
      CONJUR_AUTHN_API_KEY: 
      AWS_ACCESS_KEY_ID: 
      AWS_SECRET_ACCESS_KEY: 
    depends_on:
      - conjur
    volumes:
      - pg_admin:/var/run/postgresql/
      - ./secretless.admin.yml:/config.yaml

  admin:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      http_proxy: http://admin_secretless:80
      CONJUR_APPLIANCE_URL: http://conjur
      CONJUR_ACCOUNT: dev
      CONJUR_AUTHN_TOKEN: "eyJkYXRhIjoiZHVtbXkifQo="
    volumes:
      - pg_admin:/var/run/postgresql/
      - .:/work
      - ./aws:/root/.aws:ro
    depends_on:
      - admin_secretless

  myapp_secretless:
    image: secretless
    environment:
      CONJUR_APPLIANCE_URL: http://conjur
      CONJUR_ACCOUNT: dev
      CONJUR_AUTHN_LOGIN: host/myapp
      CONJUR_AUTHN_API_KEY: 
    depends_on:
      - conjur
    volumes:
      - pg_myapp:/var/run/postgresql/
      - ./secretless.myapp.yml:/config.yaml

  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      http_proxy: http://myapp_secretless:80
    volumes:
      - .:/work
      - pg_myapp:/var/run/postgresql/
    depends_on:
      - conjur

volumes:
  pg_admin:
  pg_myapp:
