# Build settings
title: Secretless
markdown: kramdown
highlighter: rouge

is_maintenance_mode: false 

baseurl: ""
url: "" # the base hostname & protocol for your site, e.g. http://example.com

plugins:
  - jekyll-feed

liquid:
  error_mode:       strict
  strict_filters:   true
  strict_variables: false

algolia:
  application_id: F14CP7WA0Q
  index_name: secretless
  search_only_api_key: 6f5fcbd181449afb3d2e8fce4bae79e0
